version: '3.8'

services:
  tax-manager:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - tax-manager-db:/app/db:rw
      - tax-manager-uploads:/app/uploads:rw
    environment:
      - HOST=0.0.0.0
      - PORT=${BACKEND_PORT:-8000}
      - UPLOAD_DIR=/app/uploads
      - DB_DIR=/app/db
      - CLEAN_DB=${CLEAN_DB:-false}
      - REACT_APP_API_URL=http://localhost:${BACKEND_PORT:-8000}
      - REACT_APP_API_PORT=${BACKEND_PORT:-8000}
    user: "1000:1000"
    networks:
      - tax-manager-network

volumes:
  tax-manager-db:
    driver: local
  tax-manager-uploads:
    driver: local

networks:
  tax-manager-network:
    driver: bridge 